schedule:
  every: ['1d']
  class: FileCleaner

# TODO:
# concurrency: 1
# pidfile: "tmp/pids/sidekiq.pid"
# logfile: "log/sidekiq.log"
# queues:
#   - default
#   - mailers
#   - cleaner
# 
# tasks: &tasks
#   FileCleaner:
#     every: ["2h"]
#     queue: "cleaner"
#     description: 'Destroys old files on the public/uploads directory'
# 
# schedule:
#   <<: *tasks

